version: '3.8'

services:
  falco:
    image: falcosecurity/falco
    stdin_open: true
    tty: true
    privileged: true
    container_name: falco
    volumes: 
      - /var/run/docker.sock:/host/var/run/docker.sock 
      - /dev:/host/dev 
      - /proc:/host/proc:ro 
      - /boot:/host/boot:ro 
      - /lib/modules:/host/lib/modules:ro 
      - /usr:/host/usr:ro
    restart: always

  falco-event-gen:
    image: sysdig/falco-event-generator
    stdin_open: true
    tty: true
    container_name: falco-event-gen
    restart: always